# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('body', models.TextField()),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('average_view_time', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
