# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
