# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='websites',
            field=models.ManyToManyField(to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='website',
            name='average_view_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='categories',
            field=models.ManyToManyField(to='rec_app.Category'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='rec',
            name='rec1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec1+', to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='rec',
            name='rec2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec2+', to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='rec',
            name='rec3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec3+', to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='rec',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rec.url+', to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='most_viewed_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile.most_viewed_site+', to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(to='rec_app.Website'),
        ),
        migrations.AddField(
            model_name='website',
            name='users_visited',
            field=models.ManyToManyField(to='rec_app.Profile'),
        ),
    ]
