# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0002_auto_20160317_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='categories',
            field=models.ManyToManyField(blank=True, to='rec_app.Category'),
        ),
    ]
