# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_auto_20160318_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='websites',
            field=models.ManyToManyField(blank=True, to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='most_viewed_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile.most_viewed_site+', to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(blank=True, to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec1+', to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec2+', to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rec.rec3+', to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='url',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rec.url+', to='rec_app.Website'),
        ),
        migrations.AlterField(
            model_name='website',
            name='average_view_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='website',
            name='users_visited',
            field=models.ManyToManyField(blank=True, to='rec_app.Profile'),
        ),
    ]
