# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_auto_20160318_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
